server {
    listen 80;
    server_name _;

    location /api/worlds {
        alias /opt/exodia/lobby.json;
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache";
    }
}
